Feat/daily
nbennink/DiscordBot pull request #6
Opened 2020-03-18 15:20 UTC by expdani

2020-09-17 20:51 UTC, gwesseling requested changes

2020-09-17 20:51 UTC, gwesseling commented on src/controllers/daily/commands.ts
> +export default function setupDailyCommands(message: Message) {
Applied changed that are implemented with the dialogflow branche please. This isn't the right way to add a command anymore.

2020-09-17 20:51 UTC, gwesseling commented on src/controllers/daily/index.ts
> +    const daily = await getDaily(userID);
Isn't this a duplicated check/ call? Because you already check if daily isn't defined in the requestDaily method.

2020-09-17 20:51 UTC, gwesseling commented on src/controllers/daily/commands.ts
> +    const lastRequest = (daily && daily.updated_at) || new Date();
Optional channing

2020-09-17 20:51 UTC, gwesseling commented on src/controllers/daily/index.ts
> +        return {...input, id: ids[0]};
I think this is really sensitive to errors. At least add a try and catch.

2020-09-17 20:51 UTC, gwesseling commented on src/controllers/daily/index.ts
> +    let daily = await getDaily(userID);
Isn't this a duplicated check/ call? I think you should rethink the flow of the feature.

2020-09-17 20:51 UTC, gwesseling commented on src/listeners/messageListener.ts
> +                case "daily":
https://tenor.com/view/star-wars-emperor-congratulations-done-well-palpatine-gif-4953398

2020-09-18 10:46 UTC, gwesseling requested changes

2020-09-18 10:46 UTC, gwesseling commented on src/controllers/daily/index.ts
> +            return {...input, id: id};
I don't think this does what you think it supposed to do.

2020-09-18 10:46 UTC, gwesseling commented on src/controllers/daily/index.ts
> +    if (!daily) {
I still think this call should be removed. Because you already checked on this in requestDaily.

2020-09-18 10:46 UTC, gwesseling commented on src/types/daily.ts
> +export enum DAILY_COMMANDS {
Why is this necessary?

2020-09-18 11:13 UTC, nbennink commented on src/controllers/daily/commands.ts
> +    const lastRequest = (daily && daily?.updated_at) || new Date();
```suggestion
    const lastRequest = daily?.updated_at || new Date();
```

2021-01-23 19:57 UTC, gwesseling approved these changes

2021-01-28 12:20 UTC, merged